### PR TITLE
Storybook

### PR DESCRIPTION
**Pull request by Shaun2D2**

### CODE REVIEW

**Comment by Shaun2D2** [comment]
@msluther yea that would be good to add in, did you want me to implement that before we merge in or are we good to go with this PR?

**Comment by msluther** [comment]
@Shaun2D2 I definitely wouldn't block this PR on that. Its good on its own, but a follow up PR would be nice, or at least an issue to track it perhaps.

**Comment by Shaun2D2** [comment]
@msluther awesome, added in issue #38 and #39 and assigned to myself, I'll probably be able to get to that into the early new year.

Did you want me to merge this into master or is there a process to follow?

**Comment by msluther** [comment]
@Shaun2D2 Typically 2 ✅ approvals and we merge to master. Lets poke @chrishinrichs and see if there are any other comments.

**Pull request merged**
