### PR TITLE
change deprecated npm script

### PR DESCRIPTION
**Pull request by rivajunior**

### CODE REVIEW

**Comment by msluther** [comment]
What is the reasoning here?

**Comment by rivajunior** [comment]
@msluther those removed scripts are deprecated or already removed in latest release of NPM. [See docs](https://docs.npmjs.com/cli/v6/using-npm/scripts)

**Comment by msluther** [comment]
@rivajunior Yes, `prepublish` is, but the rest you have removed are not.  And I suspect that what was there for `prepublish` should actually be `prepublishOnly` since we don't actually need those to run at install time.

**Comment by rivajunior** [comment]
@msluther you are right. I've fixed that. And I will make another PR to add react 17 as supported version

**Review by rxmarbles — APPROVED** [review]

**Pull request merged**
